namePrefix: dev-
commonAnnotations:
  note: Hello, I am dev!
resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# labels:
# - includeSelectors: true
#   pairs:
#     org: acmeCorporation
#     variant: production
patches:
- path: app.yaml
