apiVersion: v1
data:
  changelog.yaml: |+
    databaseChangeLog:
    - changeSet:
        id: 1689337429090-1
        author: kostas (generated)
        changes:
        - createTable:
            columns:
            - column:
                autoIncrement: true
                constraints:
                  nullable: false
                  primaryKey: true
                  primaryKeyName: customers_pkey
                name: customer_id
                type: INTEGER
            - column:
                name: customer_name
                type: VARCHAR
            - column:
                name: customer_surname
                type: VARCHAR
            - column:
                name: customer_number
                type: VARCHAR
            - column:
                name: phone
                type: VARCHAR
            - column:
                name: mobile
                type: VARCHAR
            tableName: customers
    - changeSet:
        id: 2
        author: kostas
        changes:
        - addColumn:
            tableName: customers
            columns:
            - column:
                name: home
                type: VARCHAR


kind: ConfigMap
metadata:
  annotations:
    note: Hello, I am dev!
  labels:
    app: hello
  name: dev-asdliquibase-changelog
  namespace: orders
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    note: Hello, I am dev!
  labels:
    app: hello
  name: dev-python-app
  namespace: orders
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    note: Hello, I am dev!
  labels:
    app: hello
  name: dev-python-app
  namespace: orders
spec:
  selector:
    matchLabels:
      app: hello
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        note: Hello, I am dev!
      labels:
        app: hello
    spec:
      containers:
      - env:
        - name: ENV
          value: dev
        - name: ENABLE_TELEMETRY
          value: "False"
        - name: OTEL_TRACES_EXPORTER
          value: console,otlp
        - name: OTEL_SERVICE_NAME
          value: demo-flask
        - name: OTEL_METRICS_EXPORTER
          value: none
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://opentelemetry-collector.monitoring.svc.cluster.local:4317
        - name: OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_REQUEST
          value: Accept-Encoding,User-Agent,Referer
        - name: OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_RESPONSE
          value: Last-Modified,Content-Type
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: root
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              key: mongodb-root-password
              name: mongodb
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongodb-headless
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-password
              name: postgresql
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_URL
          value: postgresql
        image: konkerama/k8s-application
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        name: python-app
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
      initContainers:
      - command:
        - liquibase
        - update
        - --changeLogFile=changelog/changelog.yaml
        env:
        - name: LIQUIBASE_LOG_LEVEL
          value: FINE
        - name: LIQUIBASE_COMMAND_URL
          value: jdbc:postgresql://postgres:5432/postgres?autoReconnect=true&useSSL=false
        - name: LIQUIBASE_COMMAND_USERNAME
          value: postgres
        - name: LIQUIBASE_COMMAND_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-password
              name: postgresql
        image: liquibase/liquibase:latest
        name: liquibase
        volumeMounts:
        - mountPath: /liquibase/changelog
          name: liquibase-changelog-volume
      volumes:
      - configMap:
          name: dev-asdliquibase-changelog
        name: liquibase-changelog-volume
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    note: Hello, I am dev!
  labels:
    app: hello
  name: dev-python-app
  namespace: orders
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dev-python-app
