apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: orders
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: client
          ports:
            - containerPort: 8080
          env:
          - name: ENV
            value: "dev"
          - name: OTEL_TRACES_EXPORTER
            value: "console,otlp"
          - name: OTEL_SERVICE_NAME
            value: "demo-flask"
          - name: OTEL_METRICS_EXPORTER
            value: "none"
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://opentelemetry-collector.monitoring.svc.cluster.local:4317"
          - name: OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_REQUEST
            value: "Accept-Encoding,User-Agent,Referer"
          - name: OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_RESPONSE
            value: "Last-Modified,Content-Type"
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-username
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom: 
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-password
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom: 
              configMapKeyRef:
                name: mongodb-configmap
                key: database_url
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-root-username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-root-password
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: postgres-configmap
                key: postgres-dbname
          - name: POSTGRES_URL
            value: postgres.customer-product.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: orders
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
kind: Pod
apiVersion: v1
metadata:
  name: foo-app
  namespace: orders
  labels:
    app: app1
    component: foo1
spec:
  containers:
  - name: foo-app
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text=hello from namespace default"
---
kind: Service
apiVersion: v1
metadata:
  name: foo1
  namespace: orders
spec:
  type: LoadBalancer
  selector:
    component: foo1
  ports:
  - port: 5678