apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: app
build:
  artifacts:
    - image: client
      docker:
        dockerfile: Dockerfile
manifests:
#   rawYaml:
#     - k8s/app.yaml
  kustomize:
    paths:
    - k8s/overlays/dev/

