apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: orders
spec:
  template:
    spec:
      containers:
        - name: python-app
          image: client
          env:
          - name: ENV
            value: "dev"
          - name: ENABLE_TELEMETRY
            value: "false"
