name: Open PR
on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
jobs:
  identify_new_version:
    name: Identify New Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          repository: konkerama/k8s-project
          token: ${{ secrets.GH_TOKEN }}

      - name: echo new tag
        run: git checkout k8s-application/v1.2.4 || git checkout -b k8s-application/v1.2.4

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com

      - name: Initialize mandatory git config
        run: |
          echo "asdf" >> asdf

      - name: Initialize mandatory git config
        run: |
          git add . 
          git commit -m "new commit"
          git push origin k8s-application/v1.2.4


      - name: Initialize mandatory git config
        run: |
          echo "${{ secrets.GH_TOKEN }}" > .githubtoken
          gh auth login --with-token < .githubtoken
          rm .githubtoken
          gh pr create --title "some title" --body "some body" --head "k8s-application/v1.2.4" --base main
