name: 'CICD'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  lint-and-test:
    name: 'Lint and Test'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pytest
        cd python
        pip install -r $(git ls-files '*requirements.txt')

    - name: Analysing the code with pylint
      run: pylint $(git ls-files '*.py') --disable=C

    # - name: Test Code
    #   run: |
    #     export ENV=${{ env.ENV_NAME }}
    #     pytest

  docker-build-push:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Install dependencies
        working-directory: python
        run: |
          python -m pip install --upgrade pip

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./src/sample-container
          push: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
          tags: konkerama/k8s-application:${{github.sha}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
